stages:
  - build 
  - test

build:
  stage: build
  tags:
    - shell
  script: 
      - sh -c '[ "git diff origin/develop package.json | wc -l" != "0" ] && docker build -t harbor.saas.com:20010/egg-passport/base . && docker push harbor.saas.com:20010/egg-passport/base || echo "package.json does not change"'

test: 
  image: harbor.saas.com:20010/egg-passport/base
  stage: test
  except:
    - develop
  tags:
    - docker registry
  before_script: 
    - ln -s /app/node_modules node_modules
  script: 
    - npm test
    - npm run lint